replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret-tabby
      hosts:
        - domain.com

resources:
  limits:
    cpu: 4000m
    memory: 8192Mi
    nvidia.com/gpu: 1
  requests:
    cpu: 1000m
    memory: 4096Mi
    nvidia.com/gpu: 1

storage:
  className: "default"

env:
  DEVICE: cuda
  MODEL: TabbyML/DeepseekCoder-6.7B