kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.storage.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.className }}